# Netlify configuration for the DiversiFi app

[build]
  command = "pnpm build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--version"
  NEXT_TELEMETRY_DISABLED = "1"
  # Alpha Vantage API key for currency data
  NEXT_PUBLIC_ALPHA_VANTAGE_API_KEY = "SWNW9OUK2X6UDKVS"

[[plugins]]
  package = "@netlify/plugin-nextjs"
